<?php $value_id = (new Appointmentpro_Model_Appointmentpro())->getCurrentValueId();?>

<div class="container-fluid appointmentpro">
	<div class="container-fluid">
		<div id="wrapper" class="left-toggled">
          <div class="right-toggled">
            <div class="sidebars has-sidebar">
            <?php include(dirname(__DIR__)."/partials/menu.phtml"); ?>
            <div class="subcontent third-main-panel">
				<div class="row app-features">
					<div class="responsive-part col-md-12">
			         <div class="page-content-wrapper form-horizontal">
			            <div class="content solo-page">
		                <h3 class="title-editor border-blue text-center">
		                  <?php echo p__("appointmentpro","Locations Add"); ?>
                      <a href="/appointmentpro/location/list" id="back" class="color-blue btn sb-tour pull-right">
                              <?php echo  p__("appointmentpro", "All Locations"); ?>   </a>
		                </h3>
			              <div class="subcontent content-color container-fluid">
						         <form role="form" id="locationform" class="setup-from" action="<?php echo $this->getUrl('appointmentpro/location/save'); ?>" method="post" enctype="multipart/form-data">
        							        <input type="hidden" name="value_id" value="<?php echo $value_id; ?>">
        		                   <div class="form-group">                     
        		                      <div class="col-md-8">
        		                         
        	                          <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="name">
                                                <?php echo p__("appointmentpro", 'Name'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="name" id="name" />
                                        </div>
                                      </div>                        
        	                                
                                    <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="name">
                                                <?php echo p__("appointmentpro", 'Email'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="email" id="email" />
                                        </div>
                                      </div>                        
                                       

                                      <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="address">
                                                <?php echo p__("appointmentpro", 'Address'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="address" id="address" />
                                        </div>
                                       </div>

                                       <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="address">
                                                <?php echo p__("appointmentpro", 'Location'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <input type="text" value="" class="required input-flat" name="location" id="location" />
                                            <input type="hidden" name="latitude" id="latitude">
                                            <input type="hidden" name="longitude" id="longitude">
                                        </div>
                                       </div>

                                       <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="about_us">
                                                <?php echo p__("appointmentpro", 'About Us'); ?><span>*</span></label>
                                        </div>
                                        <div class="col-sm-8">
                                            <textarea cols="12" rows="6" class="required input-flat" name="about_us" id="about_us"></textarea>
                                        </div>
                                       </div>

                                        <div class="form-group">
                                                <div class="col-sm-4">
                                                    <label for="featured_image"><?php echo p__("appointmentpro", 'Featured Image'); ?></label>
                                                </div>
                                                <div class="col-sm-8">
                                                     <div class="location-images-container uploadImage">
                                                         <img src="/app/local/modules/appointmentpro/resources/design/desktop/flat/images/placeholder.png" width="100px" height="100px">
                                                     </div> 
                                                </div>
                                       </div>

                                        <div class="form-group">
                                            <div class="col-sm-4">
                                            </div> 
                                            <div class="col-sm-8">
                                                <label for="is_allow_accept_payment" class="checkbox-inline">
                                                    <input type="checkbox" id="is_allow_accept_payment" name="is_allow_accept_payment" value="1" class="color-blue checkbox sb-tour" />
                                                   <?php echo p__("appointmentpro", 'Allow accept payment in own account'); ?>
                                                </label>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-sm-4">
                                            </div>
                                            <div class="col-sm-8">
                                                <label for="is_active" class="checkbox-inline">
                                                    <input type="checkbox" id="is_active" name="is_active" value="1" class="color-blue checkbox sb-tour" />
                                                   <?php echo p__("appointmentpro", 'Active'); ?>
                                                </label>
                                            </div>
                                        </div>        	                             

                                        <div class="row">
                      								    <div class="col-md-12">
                      								     <button class="color-blue btn pull-right" type="submit"><?php echo p__("appointmentpro", "Save"); ?></button>
                      								    </div>
                      								</div>

                                  </div>
        			             </div>
        			          </form>
                    </div>
			          </div>
			       </div>
				   </div>
				</div>
			 </div>
		 </div>
	  </div>
	</div>
  </div>
</div>
<input style="display: none;" id="select_image" class="select_image uploader" type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">

<script type="text/javascript">

        // Load window.feature_links
    $.ajax({
        url: '/application/customization_features/links',
        method: 'GET',
        dataType: 'json',
        success: function (data) {
            window.feature_links = data;
        }
    });
    
	setTimeout(function() {
        $('#about_us').ckeditor(ckeditor_config.cms);
    }, 100);     


   $('#locationform').submit(function(e) {
          e.preventDefault();
          var formData = new FormData(this);    
        if($(this).valid()) {
            reload(this, this.action, formData, function(data) {  
                if(data.success) {
                    window.location = "<?php  echo $this->getUrl("appointmentpro/location/list"); ?>"; 
                }
            });
        }
        return false;
    }); 

    var Uploader = new Uploader();
    /*IOS screenshots */
    var image_view_template = '<?php echo str_replace("\n", "", '<div class="cms-image" style="background-image: url(#THUMBNAIL_PATH#);"><div class="image-delete"></div><img src="" class="cms-image-unit uploadImage" /><input type="hidden" name="featured_image[]" value="%IMAGE_PATH%" /></div>' ); ?>';

    $('#select_image').fileupload({
            dataType: 'json',
            add: function(e, data) {
                data.submit();
                Uploader.showProgressbar();
            },
            progressall: function(e, data) {
                Uploader.moveProgressbar(data);
            },
            fail: function (el, data) {
                Uploader.hide();
                Uploader.showError(JSON.parse(data.jqXHR.responseText).message);
            },
            done: function(e, data) {
                if (data.result.error) {
                    Uploader.hide();
                    Uploader.showError(data.result.message);
                }
                if (data.result.success) {
                    Uploader.hide();
                    var params = [];
                    params["url"] = '<?php echo $this->getUrl('template/crop/crop'); ?>';
                    params["file"] = data.result.files;
                    params["output_w"] = 560;
                    params["output_h"] = 292;
                    params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('appointmentpro/application/crop')) ?>';
                    params["uploader"] = 'Uploader';
                    Uploader.crop(params);

                    Uploader.callback = function(file) {
                           var cms_image = image_view_template;
                           cms_image = cms_image.replace("%IMAGE_PATH%", file);
                           cms_image = cms_image.replace("#THUMBNAIL_PATH#",  '<?php echo Core_Model_Directory::getTmpDirectory(); ?>/' + file);
                           $(".location-images-container").html(cms_image);
                    };
                }
            }
        });

        $(document).on("click", ".image-delete", function() {
            var el = $(this);
            el.parents(".cms-image").remove();
        });

        $(document).on("click", ".uploadImage", function() {
            $("#select_image").click();
        });

</script>

 <!-- Map Start  -->
<?php
 $api = Api_Model_Key::findKeysFor("googlemaps");
 $googlemaps_key =  $this->getApplication()->getGooglemapsKey();
 ?>
 <script type="text/javascript">     
  function initMap(){
        var autocomplete = new google.maps.places.Autocomplete($("#location")[0], {});
        google.maps.event.addListener(autocomplete, 'place_changed', function() {
            var place = autocomplete.getPlace();
             var near_place = autocomplete.getPlace();
             document.getElementById('latitude').value = near_place.geometry.location.lat();
             document.getElementById('longitude').value = near_place.geometry.location.lng();
        });
    }
 </script>
 <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=false&key=<?php echo $googlemaps_key;?>&libraries=places&callback=initMap"></script>    
<!-- Map end  -->
