<?php $value_id = (new Appointmentpro_Model_Appointmentpro())->getCurrentValueId();?>
<?php $location = $this->getLocation();  

$galleries = (new Appointmentpro_Model_LocationGallery())
                                ->findAll(['location_id' => $location->getLocationId(), 'is_delete' => 0])->toArray();
?>

<div class="container-fluid appointmentpro">
	<div class="container-fluid">
		<div id="wrapper" class="left-toggled">
          <div class="right-toggled">
            <div class="sidebars has-sidebar">
            <?php include(dirname(__DIR__)."/partials/menu.phtml"); ?>
            <div class="subcontent third-main-panel">
				<div class="row app-features">
					<div class="responsive-part col-md-12">
			         <div class="page-content-wrapper form-horizontal">
			            <div class="content solo-page">
			                <h3 class="title-editor border-blue text-center">
			                  <?php echo p__("appointmentpro","%s Gallery", $location->getName()); ?>
			                <a href="/appointmentpro/location/list" id="back" class="color-blue btn sb-tour pull-right">
                                <?php echo  p__("appointmentpro", "Back"); ?>   </a>
			                </h3>
			                <div class="subcontent content-color container-fluid">
			              
			                <form id="galleryForm" role="form" class="setup-from" action="<?php echo $this->getUrl('appointmentpro/location/savegallery'); ?>" method="post" enctype="multipart/form-data">
                           
                            <input type="hidden" name="value_id" value="<?php echo $value_id ?>">

                            <input type="hidden" name="location_id" value="<?php echo $location->getLocationId(); ?>">
                          
                            <div class="row">
								<div class="col-md-12">
				                	<div class="gallery-images-container">
				                		<?php foreach ($galleries as $key => $value) { ?>

				                	    <div class="cms-image" style="background-image: url(<?php echo '/images/application/'.$value['image']; ?>);">
				                	    	<a href="<?php echo $this->getUrl('appointmentpro/location/deletegallery').'/id/'.$value['id']; ?>" class="delete-gallery"><i class="fa fa-times"></i></a><img src="<?php echo '/images/application/'.$value['image']; ?>" class="cms-image-unit" /></div>

				                		<?php } ?>

				                		 <img class="uploadImage" src="/app/local/modules/Appointmentpro/resources/design/desktop/flat/images/placeholder.png" width="100px" height="100px">
				                	</div>
				            </div>
				           </div>

        	  			    <div class="row">
							    <div class="col-md-12">
							     <button class="color-blue btn pull-right" type="submit"><?php echo p__("appointmentpro", "Save"); ?></button>
							    </div>
							</div>

			                 </form>
			                </div>
			            </div>
			          </div>
				    </div>
			    </div>
			</div>
		</div>
	  </div>
	</div>
  </div>
</div>
<input style="display: none;" id="select_image" class="select_image uploader" type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">

<script type="text/javascript">

   $('#galleryForm').submit(function(e) {
          e.preventDefault();
          var formData = new FormData(this);    
        if($(this).valid()) {
            reload(this, this.action, formData, function(data) {  
                if(data.success) {
                    window.location = "<?php  echo $this->getUrl("appointmentpro/location/list"); ?>"; 
                }
            });
        }
        return false;
    });

   var Uploader = new Uploader();
    /*IOS screenshots */
    var image_view_template = '<?php echo str_replace("\n", "", '<div class="cms-image" style="background-image: url(#THUMBNAIL_PATH#);"><div class="image-delete"><i class="fa fa-times"></i></div><img src="" class="cms-image-unit" /><input type="hidden" name="gallery_image[]" value="%IMAGE_PATH%" /></div>' ); ?>';

    $('#select_image').fileupload({
            dataType: 'json',
            add: function(e, data) {
                data.submit();
                Uploader.showProgressbar();
            },
            progressall: function(e, data) {
                Uploader.moveProgressbar(data);
            },
            fail: function (el, data) {
                Uploader.hide();
                Uploader.showError(JSON.parse(data.jqXHR.responseText).message);
            },
            done: function(e, data) {
                if (data.result.error) {
                    Uploader.hide();
                    Uploader.showError(data.result.message);
                }
                if (data.result.success) {
                    Uploader.hide();
                    var params = [];
                    params["url"] = '<?php echo $this->getUrl('template/crop/crop'); ?>';
                    params["file"] = data.result.files;
                    params["output_w"] = 520;
                    params["output_h"] = 520;
                    params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('appointmentpro/application/crop')) ?>';
                    params["uploader"] = 'Uploader';
                    Uploader.crop(params);

                    Uploader.callback = function(file) {
                           var cms_image = image_view_template;
                           cms_image = cms_image.replace("%IMAGE_PATH%", file);
                           cms_image = cms_image.replace("#THUMBNAIL_PATH#",  '<?php echo Core_Model_Directory::getTmpDirectory(); ?>/' + file);
                           $(".gallery-images-container").append(cms_image);
                    };
                }
            }
        });

        $(document).on("click", ".image-delete", function() {
            var el = $(this);
            el.parents(".cms-image").remove();
        });

        $(document).on("click", ".uploadImage", function() {
            $("#select_image").click();
        });

		 $(document).off("click", ".delete-gallery");
	    $(document).on("click", ".delete-gallery", function (e) {
	        e.preventDefault();
	        let deleteHref = $(this).attr("href");
	        swal({
	            title: "<?php echo P__("appointmentpro", "Confirmation") ?>",
	            text: "<?php echo P__("appointmentpro", "Are you sure you want to delete this image?") ?>",
	            showCancelButton: true,
	            confirmButtonColor: '#0099C7',
	            confirmButtonText: "<?php echo P__("appointmentpro", "Yes, delete!")?>",
	            cancelButtonText: "<?php echo P__("appointmentpro", "No, go back") ?>",
	            buttons: true
	        }, function(value) {
	            if (!value) {
	                return false;
	            }

	            formget(deleteHref,
	                {},
	                function (data) {
	                    feature_form_success(data.message);
	                   // Reload only on success and when done!
	                    setTimeout(function () {
	                        location.reload();
	                    }, 1500)
	                },
	                function (data) {
	                    feature_form_error(JSON.parse(data.responseText).message);
	                },
	                false);
	        });
	    });

</script>