<div class="container-fluid appointmentpro">
    <div class="container-fluid">
        <div id="wrapper" class="left-toggled">
            <div class="right-toggled">
                <div class="sidebars has-sidebar">
                    <?php include(dirname(__DIR__) . "/partials/menu.phtml"); ?>
                    <div class="subcontent third-main-panel">
                        <div class="row app-features">
                            <div class="responsive-part col-md-12">
                                <div class="page-content-wrapper form-horizontal">
                                    <div class="content solo-page">
                                        <h3 class="title-editor border-blue text-center">
                                            <?php echo p__("appointmentpro", "Classes"); ?>
                                            <a href="/appointmentpro/class/add" id="add_category" class="color-blue btn sb-tour pull-right">
                                                <?php echo  p__("appointmentpro", "Add Class"); ?> </a>
                                        </h3>
                                        <div class="subcontent content-color container-fluid">

                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <table id="dynamic-classes" class="table content-white-bkg sb-pager" style="overflow: auto !important;">
                                                        <thead>
                                                            <tr class="border-grey">
                                                                <th style="width: 5%">
                                                                    <?php echo  p__("appointmentpro", "Id"); ?></th>
                                                                <th style="width: 10%">
                                                                    <?php echo  p__("appointmentpro", "Image"); ?></th>
                                                                <th style="width: 20%;" data-dynatable-column="name">
                                                                    <?php echo  p__("appointmentpro", "Name"); ?></th>
                                                                <th style="width: 10%;" data-dynatable-column="category_id">
                                                                    <?php echo  p__("appointmentpro", "Seates"); ?></th>
                                                                <th data-dynatable-column="service_time" style="width: 15%;">
                                                                    <?php echo  p__("appointmentpro", "Duration (Min)"); ?>
                                                                </th>
                                                                <th data-dynatable-column="class_date" style="width: 15%;">
                                                                    <?php echo  p__("appointmentpro", "Date"); ?></th>
                                                                <th data-dynatable-column="price" style="width: 10%;">
                                                                    <?php echo  p__("appointmentpro", "Price"); ?></th>
                                                                <th data-dynatable-column="schedule_type" style="width: 15%;">
                                                                    <?php echo  p__("appointmentpro", "Schedule"); ?>
                                                                </th>
                                                                <th data-dynatable-column="status" style="width: 10%;">
                                                                    <?php echo  p__("appointmentpro", "Status"); ?></th>
                                                                <th style="width: 5%">
                                                                    <?php echo  p__("appointmentpro", "Action"); ?></th>
                                                            </tr>
                                                        </thead>
                                                        <tbody class="connectedSortable"></tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.css" media="screen" rel="stylesheet" type="text/css">
<script type="text/javascript" src="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.js"></script>


<script type="text/javascript">
    var uriParams = {};
    let rowTemplate = `
    <tr class="dynarow" id="element_(ID)">
        <td>#(ID)</td>
       <td><img width="40px" src="(IMAGE)"></td>
        <td>(NAME)</td>
        <td>(SALE)/(SEATS)</td>
        <td>(TIME) <?php echo p__("appointmentpro", "Min"); ?></td>
        <td>(DATE)</td>
        <td>(PRICE)</td>
        <td>(TYPE)</td>     
        <td>(STATUS)</td>       
        <td> 
        <ul class="nav nav-pills">
              <li class="dropdown" id="asdf">
                <a class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" data-target="#" href="#"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
                <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
                   <li><a class="edit-classes" href="/appointmentpro/class/edit/id/(ID)">
                         <?php echo p__("appointmentpro", "Edit"); ?>
                        </a>
                    </li>
                    
                   <li class="divider"></li>
                   <li><a class="delete-classes" href="/appointmentpro/class/delete/id/(ID)">
                        <?php echo p__("appointmentpro", "Delete"); ?>
                       </a>
                   </li>
                </ul>
              </li>
            </ul>
         </td>
       
    </tr>`;

    function rowWriter(rowIndex, record, columns, cellWriter) {
        return rowTemplate
            .replace(/\(ID\)/g, record.service_id)
            .replace(/\(IMAGE\)/g, record.featured_image)
            .replace(/\(NAME\)/g, record.name)
            .replace(/\(PRICE\)/g, record.price_with_currency)
            .replace(/\(TIME\)/g, record.service_time)
            .replace(/\(DATE\)/g, record.class_date)
            .replace(/\(SEATS\)/g, record.capacity)
            .replace(/\(BUFFER\)/g, record.buffer_time)
            .replace(/\(TYPE\)/g, record.schedule_type)
            .replace(/\(CATEGORY\)/g, record.category_name)
            .replace(/\(CURRENCY\)/g, record.currency)
            .replace(/\(SALE\)/g, record.sale_tickets)
            .replace(/\(STATUS\)/g, record.status);
    }
    $.dynatableSetup({
        table: {
            defaultColumnIdStyle: 'noStyle'
        },
        features: {
            paginate: true,
            sort: false,
            pushState: true,
            search: true,
            recordCount: false,
            perPageSelect: false,
        },
    });

    let tableCustomers = $('#dynamic-classes');

    tableCustomers.bind('dynatable:preinit', function(e, dynatable) {
        dynatable.utility.textTransform.noStyle = function(text) {
            return text;
        };
    });

    tableCustomers.bind('dynatable:afterProcess', function(e, data) {
        uriParams = data.queries;
    });

    tableCustomers.bind('dynatable:push', function(e, dynatable) {
        uriParams = dynatable.queries;
    });

    // And on the table
    tableCustomers.dynatable({
        dataset: {
            ajax: true,
            ajaxUrl: '/appointmentpro/class/find-all',
            ajaxOnLoad: true,
            records: [],
            perPageDefault: 25
        },
        inputs: {
            processingText: '<?php echo __jss("Loading ...") ?>',
            searchPlaceholder: '<?php echo __jss("Search class ...") ?>',
            recordCountText: '<?php echo __jss("Showing") ?> ',
            filteredFrom: ' (<?php echo __jss("filtered from #TOTAL# total records") ?>)',
            recordText: '<?php echo __jss("record") ?>',
            recordTextPlural: '<?php echo __jss("records") ?>',
            textOf: '<?php echo __jss("of") ?>',
            textTo: '<?php echo __jss("to") ?>',
            queries: $('.dt-search')
        },
        writers: {
            _rowWriter: rowWriter
        }
    });

    $(document).off("click", ".delete-classes");
    $(document).on("click", ".delete-classes", function(e) {
        e.preventDefault();
        let deleteHref = $(this).attr("href");
        swal({
            title: "<?php echo P__("appointmentpro", "Confirmation") ?>",
            text: "<?php echo P__("appointmentpro", "Are you sure you want to delete this class?") ?>",
            showCancelButton: true,
            confirmButtonColor: '#0099C7',
            confirmButtonText: "<?php echo P__("appointmentpro", "Yes, delete!") ?>",
            cancelButtonText: "<?php echo P__("appointmentpro", "No, go back") ?>",
            buttons: true
        }, function(value) {
            if (!value) {
                return false;
            }

            formget(deleteHref, {},
                function(data) {
                    feature_form_success(data.message);
                    // Reload only on success and when done!
                    setTimeout(function() {
                        location.reload();
                    }, 1500)
                },
                function(data) {
                    feature_form_error(JSON.parse(data.responseText).message);
                },
                false);
        });
    });
</script>
<style>
    .table {
        width: 100%;
        overflow: auto;
    }

    .dropdown-menu {
        min-width: auto;
    }
</style>