<?php $value_id = (new Appointmentpro_Model_Appointmentpro())->getCurrentValueId();?>
<?php $category = $this->getCategory();  ?>

<div class="container-fluid appointmentpro">
	<div class="container-fluid">
		<div id="wrapper" class="left-toggled">
          <div class="right-toggled">
            <div class="sidebars has-sidebar">
            <?php include(dirname(__DIR__)."/partials/menu.phtml"); ?>
            <div class="subcontent third-main-panel">
				<div class="row app-features">
					<div class="responsive-part col-md-12">
			         <div class="page-content-wrapper form-horizontal">
			            <div class="content solo-page">
			                <h3 class="title-editor border-blue text-center">
			                  <?php echo p__("appointmentpro","Category Edit"); ?>
                        <a href="/appointmentpro/category/list" id="back" class="color-blue btn sb-tour pull-right">
                                <?php echo  p__("appointmentpro", "Back"); ?>   </a>
			                </h3>
			            <div class="subcontent content-color container-fluid">
						
						<form role="form" id="categoryform" class="setup-from" action="<?php echo $this->getUrl('appointmentpro/category/save'); ?>" method="post" enctype="multipart/form-data">
							<input type="hidden" name="value_id" value="<?php echo $value_id; ?>">
                            <input type="hidden" name="category_id" value="<?php echo $category->getCategoryId(); ?>">
		                    <div class="form-group">                     
		                      <div class="col-md-8">
		                      
                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label for="name">
                                        <?php echo p__("appointmentpro", 'Type'); ?><span>*</span></label>
                                </div>
                                <div class="col-sm-8">
                                 <div class="sb-radio-container">
                                    <label class="sb-custom-radio radio-inline">
                                        <input type="radio" name="category_for" id="category_for" value="1" class="required sb-form-radio color-blue color-blue" <?php echo $category->getCategoryFor()== 1 ? 'checked': ''; ?>>
                                        <span class="sb-radio-label"><?php echo p__("appointmentpro", 'Service'); ?>
                                         </span>
                                    </label>

                                   <label class="sb-custom-radio radio-inline">
                                        <input type="radio" name="category_for" id="category_for" value="2" class="required sb-form-radio color-blue color-blue" <?php echo $category->getCategoryFor()== 2 ? 'checked': ''; ?>>
                                        <span class="sb-radio-label"><?php echo p__("appointmentpro", 'Class'); ?>
                                         </span>
                                    </label>

                                 </div>
                                </div>
                            </div> 

                            <div class="form-group">
                                <div class="col-sm-4">
                                    <label for="name">
                                        <?php echo p__("appointmentpro", 'Name'); ?><span>*</span></label>
                                </div>
                                <div class="col-sm-8">
                                    <input type="text" value="<?php echo $category->getName(); ?>" class="required input-flat" name="name" id="name" />
                                </div>
                              </div>                        
	                            
                                <div class="form-group">
                                        <div class="col-sm-4">
                                            <label for="featured_image"><?php echo p__("appointmentpro", 'Featured Image'); ?></label>
                                        </div>
                                        <div class="col-sm-8">
                                             <div class="category-images-container uploadImage">
                                            <?php if(!empty($category->getImage())): ?>
                                                <img src="/images/application/<?php echo $category->getImage(); ?>" width="100px" height="100px">
                                            <?php else: ?>
                                                 <img src="/app/local/modules/Appointmentpro/resources/design/desktop/flat/images/placeholder.png" width="100px" height="100px">
                                             <?php endif; ?>
                                             </div> 
                                        </div>
                               </div>  

	                           <div class="form-group">
                                    <div class="col-sm-12">
                                        <label for="is_active" class="checkbox-inline">
                                            <input type="checkbox" id="is_active" name="is_active" value="1" class="color-blue checkbox" <?php echo $category->getIsActive()== 1 ? 'checked': ''; ?>>
                                           <?php echo p__("appointmentpro", 'Active'); ?>
                                        </label>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <div class="col-sm-12">
                                        <label for="top_category" class="checkbox-inline">
                                            <input type="checkbox" id="top_category" name="top_category" value="1" class="color-blue checkbox " <?php echo $category->getTopCategory()== 1 ? 'checked': ''; ?> />
                                           <?php echo p__("appointmentpro", 'Display at Home'); ?>
                                        </label>
                                    </div>
                                </div>

                                
                                <div class="row">
								    <div class="col-md-12">
								     <button class="color-blue btn pull-right" type="submit"><?php echo p__("appointmentpro", "Save"); ?></button>
								    </div>
								 </div>
                                </div>
	      		                </div>
			                    </form>
                            </div>
			            </div>
			          </div>
				   </div>
				</div>
			 </div>
		 </div>
	  </div>
	</div>
  </div>
</div>

<input style="display: none;" id="select_image" class="select_image uploader" type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">


<script type="text/javascript">
 

   $('#categoryform').submit(function(e) {
          e.preventDefault();
          var formData = new FormData(this);    
        if($(this).valid()) {
            reload(this, this.action, formData, function(data) {  
                if(data.success) {
                 window.location = "<?php  echo $this->getUrl("appointmentpro/category/list"); ?>"; 
                }
            });
        }
        return false;
    }); 


   
    var Uploader = new Uploader();
    /*IOS screenshots */
    var image_view_template = '<?php echo str_replace("\n", "", '<div class="cms-image" style="background-image: url(#THUMBNAIL_PATH#);"><div class="image-delete"></div><img src="" class="cms-image-unit uploadImage" /><input type="hidden" name="featured_image[]" value="%IMAGE_PATH%" /></div>' ); ?>';

    $('#select_image').fileupload({
            dataType: 'json',
            add: function(e, data) {
                data.submit();
                Uploader.showProgressbar();
            },
            progressall: function(e, data) {
                Uploader.moveProgressbar(data);
            },
            fail: function (el, data) {
                Uploader.hide();
                Uploader.showError(JSON.parse(data.jqXHR.responseText).message);
            },
            done: function(e, data) {
                if (data.result.error) {
                    Uploader.hide();
                    Uploader.showError(data.result.message);
                }
                if (data.result.success) {
                    Uploader.hide();
                    var params = [];
                    params["url"] = '<?php echo $this->getUrl('template/crop/crop'); ?>';
                    params["file"] = data.result.files;
                    params["output_w"] = 120;
                    params["output_h"] = 120;
                    params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('appointmentpro/application/crop')) ?>';
                    params["uploader"] = 'Uploader';
                    Uploader.crop(params);

                    Uploader.callback = function(file) {
                           var cms_image = image_view_template;
                           cms_image = cms_image.replace("%IMAGE_PATH%", file);
                           cms_image = cms_image.replace("#THUMBNAIL_PATH#",  '<?php echo Core_Model_Directory::getTmpDirectory(); ?>/' + file);
                           $(".category-images-container").html(cms_image);
                    };
                }
            }
        });

        $(document).on("click", ".image-delete", function() {
            var el = $(this);
            el.parents(".cms-image").remove();
        });


        $(document).on("click", ".uploadImage", function() {
            $("#select_image").click();
        });


</script>