<?php $value_id = (new Appointmentpro_Model_Appointmentpro())->getCurrentValueId(); ?>
<?php
$categories = (new Appointmentpro_Model_Category())
    ->findByValueId($value_id);

$range = range(5, 360, 5);
$st_values = array_combine($range, $range);

$range = range(0, 55, 5);
$bt_values = array_combine($range, $range);

$locations = (new Appointmentpro_Model_Location())
    ->findByValueId($value_id);

?>

<div class="container-fluid appointmentpro">
    <div class="container-fluid">
        <div id="wrapper" class="left-toggled">
            <div class="right-toggled">
                <div class="sidebars has-sidebar">
                    <?php include(dirname(__DIR__) . "/partials/menu.phtml"); ?>
                    <div class="subcontent third-main-panel">
                        <div class="row app-features">
                            <div class="responsive-part col-md-12">
                                <div class="page-content-wrapper form-horizontal">
                                    <div class="content solo-page">
                                        <h3 class="title-editor border-blue text-center">
                                            <?php echo p__("appointmentpro", "Provider Add"); ?>
                                            <a href="/appointmentpro/provider/list" id="back" class="color-blue btn sb-tour pull-right">
                                                <?php echo  p__("appointmentpro", "Back"); ?> </a>
                                        </h3>
                                        <div class="subcontent content-color container-fluid">
                                            <form role="form" id="providerform" class="setup-from" action="<?php echo $this->getUrl('appointmentpro/provider/save'); ?>" method="post" enctype="multipart/form-data">

                                                <input type="hidden" name="value_id" value="<?php echo $value_id; ?>">

                                                <div class="form-group">
                                                    <div class="col-md-8">
                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="name">
                                                                    <?php echo p__("appointmentpro", 'Name'); ?><span>*</span></label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <input type="text" value="" class="required input-flat" name="name" id="name" />
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="email">
                                                                    <?php echo p__("appointmentpro", 'Email'); ?><span>*</span></label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <input type="text" value="" class="required input-flat" name="email" id="email" />
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="mobile_number">
                                                                    <?php echo p__("appointmentpro", 'Mobile Number'); ?><span>*</span></label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <input placeholder="e.g +33629384712" type="text" value="" class="required input-flat" name="mobile_number" id="mobile_number" />
                                                                <p>(<?php echo p__("appointmentpro", 'Mobile number must be add with country code'); ?>)</p>
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="designation">
                                                                    <?php echo p__("appointmentpro", 'Designation'); ?><span>*</span></label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <input type="text" value="" class="required input-flat" name="designation" id="designation" />
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="profile_image"><?php echo p__("appointmentpro", 'Image'); ?></label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <div class="provider-images-container uploadImage">
                                                                    <img src="/app/local/modules/Appointmentpro/resources/design/desktop/flat/images/placeholder.png" width="100px" height="100px">
                                                                </div>
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="about_us">
                                                                    <?php echo p__("appointmentpro", 'Description'); ?><span>*</span></label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <textarea cols="12" rows="6" class="required input-flat" name="description" id="description"></textarea>
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label>
                                                                    <?php echo p__("appointmentpro", 'Active'); ?>
                                                                </label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <label for="is_active" class="checkbox-inline">
                                                                    <input type="checkbox" id="is_active" name="is_active" value="1" class="color-blue checkbox sb-tour" />
                                                                </label>
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label>
                                                                    <?php echo p__("appointmentpro", 'Display at Home'); ?>
                                                                </label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <label for="is_popular" class="checkbox-inline">
                                                                    <input type="checkbox" id="is_popular" name="is_popular" value="1" class="color-blue checkbox sb-tour" />
                                                                </label>
                                                            </div>
                                                        </div>

                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="is_mobile_user">
                                                                    <?php echo p__("appointmentpro", 'Enable Mobile Control'); ?>
                                                                    (<span class="text-info"><i class="fa fa-lock"></i>
                                                                        <?php echo p__('appointmentpro', 'PREMIUM'); ?></span>)
                                                                </label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <label for="is_mobile_user" class="checkbox-inline">
                                                                    <?php if (\Appointmentpro\Extension::isEnabled('classes')) { ?>
                                                                        <input type="checkbox" id="is_mobile_user" name="is_mobile_user" value="1" class="color-blue checkbox sb-tour" />
                                                                    <?php } else { ?>
                                                                        <input type="checkbox" class="color-blue checkbox sb-tour" disabled="disabled" />
                                                                    <?php } ?>
                                                                </label>
                                                            </div>
                                                        </div>


                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="user_role">
                                                                    <?php echo p__("appointmentpro", 'Role'); ?>
                                                                </label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <select class="required styled-select color-blue" name="user_role" id="user_role">
                                                                    <option value="manager"><?php echo p__("appointmentpro", 'Manager'); ?></option>
                                                                    <option value="provider"><?php echo p__("appointmentpro", 'Provider'); ?></option>
                                                                </select>
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="calendar_header_bg">
                                                                    <?php echo p__("appointmentpro", 'Calendar Header Background'); ?>
                                                                </label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <input type="color" name="calendar_header_bg" id="calendar_header_bg" value="#0096bf">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="calendar_header_color">
                                                                    <?php echo p__("appointmentpro", 'Calendar Header Color'); ?>
                                                                </label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <input type="color" name="calendar_header_color" id="calendar_header_color" value="#ffffff">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="calendar_body_bg">
                                                                    <?php echo p__("appointmentpro", 'Calendar Body Background'); ?>
                                                                </label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <input type="color" name="calendar_body_bg" id="calendar_body_bg" value="#6abdd4">
                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="col-sm-4">
                                                                <label for="calendar_body_color">
                                                                    <?php echo p__("appointmentpro", 'Calendar Body Color'); ?>
                                                                </label>
                                                            </div>
                                                            <div class="col-sm-8">
                                                                <input type="color" name="calendar_body_color" id="calendar_body_color" value="#ffffff">
                                                            </div>
                                                        </div>

                                                        <div class="row">
                                                            <div class="col-md-12">
                                                                <button class="color-blue btn pull-right" type="submit"><?php echo p__("appointmentpro", "Save"); ?></button>
                                                            </div>
                                                        </div>

                                                    </div>

                                                    <div class="col-md-4">
                                                        <div class="form-group">
                                                            <div class="col-sm-12">
                                                                <h4>
                                                                    <?php echo p__("appointmentpro", 'Locations'); ?>:
                                                                </h4>
                                                            </div>
                                                        </div>
                                                        <?php foreach ($locations as $key => $value) { ?>
                                                            <div class="form-group">
                                                                <div class="col-sm-12">
                                                                    <label class="radio-inline">
                                                                        <input type="radio" id="location" name="location" value="<?php echo $value->getLocationId(); ?>" class="color-blue radio sb-tour" />
                                                                        <?php echo $value->getName(); ?> (<?php echo $value->getAddress(); ?>)
                                                                    </label>

                                                                </div>
                                                            </div>
                                                        <?php } ?>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<input style="display: none;" id="select_image" class="select_image uploader" type="file" name="files[]" data-url="<?php echo $this->getUrl('template/crop/upload'); ?>">

<script type="text/javascript">
    // Load window.feature_links
    $.ajax({
        url: '/application/customization_features/links',
        method: 'GET',
        dataType: 'json',
        success: function(data) {
            window.feature_links = data;
        }
    });

    setTimeout(function() {
        $('#description').ckeditor(ckeditor_config.cms);
    }, 100);

    $('#providerform').submit(function(e) {
        e.preventDefault();
        var formData = new FormData(this);
        if ($(this).valid()) {
            reload(this, this.action, formData, function(data) {
                if (data.success) {
                    window.location = "<?php echo $this->getUrl("appointmentpro/provider/list"); ?>";
                }
            });
        }
        return false;
    });


    var Uploader = new Uploader();
    /*IOS screenshots */
    var image_view_template = '<?php echo str_replace("\n", "", '<div class="cms-image" style="background-image: url(#THUMBNAIL_PATH#);"><div class="image-delete"></div><img src="" class="cms-image-unit uploadImage" /><input type="hidden" name="profile_image[]" value="%IMAGE_PATH%" /></div>'); ?>';

    $('#select_image').fileupload({
        dataType: 'json',
        add: function(e, data) {
            data.submit();
            Uploader.showProgressbar();
        },
        progressall: function(e, data) {
            Uploader.moveProgressbar(data);
        },
        fail: function(el, data) {
            Uploader.hide();
            Uploader.showError(JSON.parse(data.jqXHR.responseText).message);
        },
        done: function(e, data) {
            if (data.result.error) {
                Uploader.hide();
                Uploader.showError(data.result.message);
            }
            if (data.result.success) {
                Uploader.hide();
                var params = [];
                params["url"] = '<?php echo $this->getUrl('template/crop/crop'); ?>';
                params["file"] = data.result.files;
                params["output_w"] = 120;
                params["output_h"] = 120;
                params["output_url"] = '<?php echo str_replace('/', '$', $this->getUrl('appointmentpro/application/crop')) ?>';
                params["uploader"] = 'Uploader';
                Uploader.crop(params);

                Uploader.callback = function(file) {
                    var cms_image = image_view_template;
                    cms_image = cms_image.replace("%IMAGE_PATH%", file);
                    cms_image = cms_image.replace("#THUMBNAIL_PATH#", '<?php echo Core_Model_Directory::getTmpDirectory(); ?>/' + file);
                    $(".provider-images-container").html(cms_image);
                };
            }
        }
    });

    $(document).on("click", ".image-delete", function() {
        var el = $(this);
        el.parents(".cms-image").remove();
    });

    $(document).on("click", ".uploadImage", function() {
        $("#select_image").click();
    });
</script>