<?php $value_id = (new Appointmentpro_Model_Appointmentpro())->getCurrentValueId();?>
<?php $defaultDays = (new Appointmentpro_Model_Appointmentpro())->getDefaultDays();
$provider = $this->getProvider();
  
$times = Appointmentpro_Model_Utils::timeOptions();

$modelTiming = (new Appointmentpro_Model_ProviderTiming());  
$modelTiming->find(['provider_id'=> $provider->getProviderId(), 'location_id'=> $provider->getLocationId()]);
if (!$modelTiming->getId()) {
	$modelTiming->setProviderId($provider->getProviderId());
	$modelTiming->setLocationId($provider->getLocationId());
	$modelTiming->save();
}

$business_timing = Siberian_Json::decode($modelTiming->getTiming());
$day_break_template = Appointmentpro_Model_ProviderTiming::$day_break_template;
$date_break_template = Appointmentpro_Model_ProviderTiming::$date_break_template;
?>


<div class="container-fluid appointmentpro">
	<div class="container-fluid">
		<div id="wrapper" class="left-toggled">
          <div class="right-toggled">
            <div class="sidebars has-sidebar">
            <?php include(dirname(__DIR__)."/partials/menu.phtml"); ?>
            <div class="subcontent third-main-panel">
		    <?php if($provider->getLocationId()): ?>
			  <form role="form" id="providerform" class="setup-from" action="<?php echo $this->getUrl('appointmentpro/provider/savebussiness'); ?>" method="post" enctype="multipart/form-data">

				<div class="row app-features">
					<div class="responsive-part col-md-12">
			         <div class="page-content-wrapper form-horizontal">
			            <div class="content solo-page">
			                <h3 class="title-editor border-blue text-center">
			                  <?php echo p__("appointmentpro","Set %s Bussiness Hours", $provider->getName());?>
                        	<a href="/appointmentpro/provider/list" id="back" class="color-blue btn sb-tour pull-right">
                                <?php echo  p__("appointmentpro", "Back"); ?>   
                            </a>
			                </h3>
			           <div class="subcontent content-color container-fluid">
					   	<input type="hidden" name="value_id" value="<?php echo $value_id; ?>">
	          			 
	          			 <input type="hidden" name="provider_id" value="<?php echo $provider->getProviderId(); ?>">
	          			 <input type="hidden" name="location_id" value="<?php echo $provider->getLocationId(); ?>">

							<div class="row">
							    <div class="col-md-3">
							    	 <h4><?php echo p__("appointmentpro", "Days"); ?></h4>
							    </div>
							    <div class="col-md-3">
							    	 <h4><?php echo p__("appointmentpro", "Working"); ?></h4>
							    </div>
							    <div class="col-md-3">
							    	 <h4><?php echo p__("appointmentpro", "Start time"); ?></h4>
							    </div>
							    <div class="col-md-3">
							    	 <h4><?php echo p__("appointmentpro", "End time"); ?></h4>
							    </div>
							</div>

	          				<?php foreach ($defaultDays as $key => $dayValue) { ?>	
                            	<div class="row">
								    <div class="col-md-3">
								     
			                                  <label>
			                                        <?php echo  p__("appointmentpro", ucfirst($dayValue)); ?></label>
			                                <input type="hidden" name="timing[is_active][<?php echo $dayValue; ?>]" value="0">
			                            
								    </div>
								    <div class="col-md-3">
								     	<div class="form-group">
			                                <input type="checkbox" data-day="<?php echo $dayValue; ?>" id="is_active_<?php echo $dayValue; ?>" name="timing[is_active][<?php echo $dayValue; ?>]" value="1" class="color-blue checkbox sb-tour" <?php echo $business_timing['is_active'][$dayValue] == 1 ? 'checked': ''; ?> />
			                                
			                            </div>
								    </div>
								    <div class="col-md-3">
								      <div class="form-group">
								      	<div class="col-md-6">
			                              <select class="required styled-select color-blue" name="timing[from_time][<?php echo $dayValue; ?>]" id="from_time_<?php echo $dayValue; ?>">
                                            <?php 
                                               foreach ($times as $key => $value) { ?>
                                                    <option value="<?php echo $key; ?>" <?php echo $business_timing['from_time'][$dayValue] == $key ? 'selected': ''; ?>>
                                                     <?php echo $value; ?>
                                                    </option>
                                            <?php } ?>
                                     		</select>
                                     	</div>
			                           </div>
								    </div>
								    <div class="col-md-3">
								      <div class="form-group">
								     	<div class="col-md-6">
			                              <select class="required styled-select color-blue" name="timing[to_time][<?php echo $dayValue; ?>]" id="to_time_<?php echo $dayValue; ?>">
                                            <?php 
                                               foreach ($times as $key => $value) { ?>
                                                    <option value="<?php echo $key; ?>" <?php echo $business_timing['to_time'][$dayValue] == $key ? 'selected': ''; ?>>
                                                     <?php echo $value; ?>
                                                    </option>
                                            <?php } ?>
                                     		</select>
                                     	  </div>
			                            </div>
								    </div>
								</div>
							<?php } ?>
                            </div>
                         </div>
			          </div>
				   </div>
				</div>

				<div class="row app-features">
					<div class="responsive-part col-md-12">
			         <div class="page-content-wrapper form-horizontal">
			            <div class="content solo-page">
			                <h3 class="title-editor border-blue text-center">
			                  <?php echo p__("appointmentpro","Set %s Date breaks/Holidays", $provider->getName());?>
			                </h3>
                             <div class="subcontent content-color container-fluid">

							    <div class="form-group">
	                                <div class="col-sm-2">
	                                    <label for="name">
	                                        <?php echo p__("appointmentpro", 'Select Date'); ?></label>
	                                </div>
	                                <div class="col-sm-4">
	                                    <input type="text" value="" class="input-flat" name="break_date" id="break_date" autocomplete="off" />
	                                </div>
	                                 <div class="col-sm-6">
	                                 	<a id='select-break-date' class="color-blue btn">
	                                 		<?php echo p__("appointmentpro", 'Ok'); ?></a>
	                                 </div>
	                              </div>                        
	                            
	                            <div class="break-date-container">
	                            	<?php foreach ($business_timing['date_break'] as $key => $value) {
	                            		 echo str_replace('#DATE#', $value,$date_break_template);
	                            	} ?>
	                            </div>
                             
                              </div>
				            </div>
				        </div>
				    </div>
				</div>

				<div class="row app-features">
					<div class="responsive-part col-md-12">
			         <div class="page-content-wrapper form-horizontal">
			            <div class="content solo-page">
			                <h3 class="title-editor border-blue text-center">
			                  <?php echo p__("appointmentpro","Set %s Day breaks", $provider->getName());?>
			                </h3>
                             <div class="subcontent content-color container-fluid">

							    <div class="form-group">
	                                <div class="col-sm-2">
	                                	<select class="styled-select color-blue" name="timing_day_breaks" id="break_day">
	                                		<option value=""><?php echo p__("appointmentpro", "Select Day"); ?>
	                                		</option>
                                            <?php 
                                               foreach ($defaultDays as $key => $value) { ?>
                                                    <option value="<?php echo $value; ?>">
                                                     <?php echo $value; ?>
                                                    </option>
                                            <?php } ?>
                                     		</select>
	                                 </div>
	                                 <div class="col-sm-2">
	                                  	 <select class="styled-select color-blue" name="timing_start_time" id="day_start_time">
                                            <?php 
                                               foreach ($times as $key => $value) { ?>
                                                    <option value="<?php echo $key; ?>">
                                                     <?php echo $value; ?>
                                                    </option>
                                            <?php } ?>
                                     		</select>
	                                 </div>
	                                 <div class="col-sm-1 text-center">
	                                 	<?php echo p__("appointmentpro", "To"); ?>
	                                 </div>
	                                  <div class="col-sm-2">
	                                  	 <select class="styled-select color-blue" name="timing_end_time" id="day_end_time">
                                            <?php 
                                               foreach ($times as $key => $value) { ?>
                                                    <option value="<?php echo $key; ?>">
                                                     <?php echo $value; ?>
                                                    </option>
                                            <?php } ?>
                                     		</select>
	                                 </div>
	                                 <div class="col-sm-2">
	                                 	 <a id='day_break_add' class="day_break_add color-blue btn">
	                                 		<?php echo p__("appointmentpro", 'Add'); ?></a>
	                                 </div>
	                              </div>                        
	                            
	                            <div class="break-day-container">
                                  <?php  echo (new	Appointmentpro_Model_ProviderTiming)->setDayBreak($business_timing['day_breaks']);
                                 ?>
	                             </div>
                             
                              </div>
				            </div>
				        </div>
				    </div>
				</div>

				<div class="row">
				   <div class="col-md-12 remove-message-warring" style="display: none;">
					 	<p class="alert alert-warning small"><?php echo p__("appointmentpro", "Please note that you need to click the Save button to commit the changes"); ?>.</p>
				    </div>
				    <div class="col-md-12">
				     <button class="color-blue btn pull-right" type="submit"><?php echo p__("appointmentpro", "Save"); ?></button>
				    </div>
				</div>
				</form>

				<?php else: ?>
					<div class="row">
					   <div class="col-md-12">
						 	<p class="alert alert-warning small text-center">
						 		<?php echo p__("appointmentpro", "Please add a Location for add a business hours"); ?>. 
						 		<a href="/appointmentpro/provider/edit/id/<?php echo $provider->getProviderId(); ?>" id="back" class=""><?php echo p__("appointmentpro", "Click here"); ?></a>
						 	</p>
					    </div>
					</div>
				<?php endif; ?>

			 </div>
		 </div>
	  </div>
	</div>
  </div>
</div>


<script type="text/javascript">
	 
	     $(".day_break_add").on("click", function() {
            var day = $("#break_day");
            var start_time = $("#day_start_time");
            var end_time = $("#day_end_time");
            if(day.val() == "" || start_time.val() == "" || end_time.val() == "") {
                alert("<?php echo p__("appointmentpro", "You must select all values."); ?>");
                return;
            }

            var _id = $(".day-break").length + 1;
            var _day = day.val();
            var _start_time = start_time.val();
            var _end_time = end_time.val();
            var _day_text = day.find("option[value='"+_day+"']").text();
            var _start_text = start_time.find("option[value='"+_start_time+"']").text();
            var _end_text = end_time.find("option[value='"+_end_time+"']").text();
            var _date = _day_text+", "+_start_text+" to "+_end_text;
            var day_break_template = '<?php echo $day_break_template;?>'
            var label =  day_break_template
            	.replace(/#DATE#/g, _date)
                .replace(/#ID#/g, _id)
                .replace(/#DAY#/g, _day)
                .replace(/#START_TIME#/g, _start_time)
                .replace(/#END_TIME#/g, _end_time);

            $(".break-day-container").append(label);

            day.val("");
            start_time.val("");
            end_time.val("");
            $('.remove-message-warring').show();
        });

   $('#providerform').submit(function(e) {
          e.preventDefault();
          var formData = new FormData(this);    
        if($(this).valid()) {
            reload(this, this.action, formData, function(data) {  
                if(data.success) {
                   location.reload();
                }
            });
        }
        return false;
    }); 


   $(document).ready(function() {
     	var date_break_template = '<?php echo $date_break_template; ?>';
     	var disableSpecificDates = function(date) {
		    var values = $(".break-date-container input[name='timing[date_break][]']")
		        .map(function() { return this.value;})
		        .toArray();
		    var string = $.datepicker.formatDate("dd/mm/yy", date);
		    return [values.indexOf(string) == -1];
		};

       
        if($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']) {
            $.datepicker.setDefaults($.datepicker.regional['<?php echo Core_Model_Language::getCurrentLanguageDatepicker(); ?>']);
        } else {
            $.datepicker.setDefaults($.datepicker.regional['en']);
        }
        $( "#break_date" ).datepicker({
            changeMonth: true,
            changeYear: true,
            numberOfMonths: 1,            
            dateFormat: 'dd/mm/yy',
            onSelect: function(date, instance) {
                $(this).data('datepicker').inline = true;
                $(this).datepicker("refresh");
            },
            onClose: function( selectedDate ) {
                $(this).data('datepicker').inline = false;
            },
            beforeShowDay: function(date) {
                return disableSpecificDates(date);
            }
        });


   		$(document).on("click", "#select-break-date", function() {
   			 var break_date = $('#break_date').val();
   			 $(".break-date-container").append(date_break_template.replace(/\#DATE\#/g, break_date));
   			 $('#break_date').val('');
   			 $('.remove-message-warring').show();
        });

         $(document).on("click","i.remove_date_break",function() {
	        $(this).parents("div.date-break").fadeOut(200, function() { $(this).remove();});
	        $('.remove-message-warring').show();
	    });

       $(document).on("click","i.remove_day_break",function() {
	        $(this).parents("div.day-break").fadeOut(200, function() { $(this).remove();});
	        $('.remove-message-warring').show();
	    });

    });

</script>
<style type="text/css">
	.remove_date_break, .remove_day_break {
	    margin-left: 10px;
	}
</style>