<div class="container-fluid appointmentpro">
    <div class="container-fluid">
        <div id="wrapper" class="left-toggled">
            <div class="right-toggled">
                <div class="sidebars has-sidebar">
                    <?php include(dirname(__DIR__)."/partials/menu.phtml"); ?>
                    <div class="subcontent third-main-panel">
                        <div class="row app-features">
                            <div class="responsive-part col-md-12">
                                <div class="page-content-wrapper form-horizontal">
                                    <div class="content solo-page">
                                        <h3 class="title-editor border-blue text-center">
                                            <?php echo p__("appointmentpro","Providers"); ?>
                                            <a href="/appointmentpro/provider/add" id="add_provider"
                                                class="color-blue btn sb-tour pull-right">
                                                <?php echo  p__("appointmentpro", "Add Provider"); ?> </a>
                                        </h3>
                                        <div class="subcontent content-color container-fluid">

                                            <div class="form-group">
                                                <div class="col-md-12">
                                                    <table id="dynamic-provider"
                                                        class="table content-white-bkg sb-pager">
                                                        <thead>
                                                            <tr class="border-grey">
                                                                <th style="width: 2%"></th>
                                                                <th style="width: 5%">
                                                                    <?php echo  p__("appointmentpro", "Id"); ?></th>
                                                                <th style="width: 10%">
                                                                    <?php echo  p__("appointmentpro", "Image"); ?></th>
                                                                <th style="width: 15%;">
                                                                    <?php echo  p__("appointmentpro", "Name"); ?></th>
                                                                <th style="width: 15%;">
                                                                    <?php echo  p__("appointmentpro", "Designation"); ?>
                                                                </th>
                                                                <th style="width: 10%">
                                                                    <?php echo  p__("appointmentpro", "Role"); ?></th>
                                                                <th style="width: 15%;">
                                                                    <?php echo  p__("appointmentpro", "Email"); ?></th>
                                                                <th style="width: 20%;">
                                                                    <?php echo  p__("appointmentpro", "Location"); ?>
                                                                </th>
                                                                <th style="width: 5%;">
                                                                    <?php echo  p__("appointmentpro", "Status"); ?></th>
                                                                <th style="width: 5%">
                                                                    <?php echo  p__("appointmentpro", "Action"); ?></th>
                                                            </tr>
                                                        </thead>
                                                        <tbody class="connectedSortable"></tbody>
                                                    </table>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<link href="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.css" media="screen" rel="stylesheet"
    type="text/css">
<script type="text/javascript" src="/app/sae/design/desktop/flat/js/dynatable/jquery.dynatable.js"></script>


<script type="text/javascript">
var uriParams = {};
let rowTemplate = `
    <tr class="dynarow" id="element_(ID)">
        <td><i class="fa fa-arrows" aria-hidden="true"></i></td>
        <td>#(ID)</td>
        <td><img width="40px" src="(IMAGE)"></td>
        <td>(NAME)</td>
        <td>(DESIGNATION)</td>
        <td>(ROLE) <i class="fa fa-mobile (MOBILEUSER)" aria-hidden="true"></i></td>
        <td>(EMAIL)</td>
        <td>(LOCATION)</td>
        <td>(ISACTIVE)</td>       
        <td> 
        <ul class="nav nav-pills">
              <li class="dropdown" id="asdf">
                <a class="dropdown-toggle" id="drop4" role="button" data-toggle="dropdown" data-target="#" href="#"><i class="fa fa-ellipsis-v" aria-hidden="true"></i></a>
                <ul id="menu1" class="dropdown-menu" role="menu" aria-labelledby="drop4">
                    <li><a class="edit-provider" href="/appointmentpro/provider/edit/id/(ID)">
                         <?php echo p__("appointmentpro", "Edit"); ?>
                        </a>
                    </li>
                    <li><a class="" href="/appointmentpro/provider/bussiness/id/(ID)">
                         <?php echo p__("appointmentpro", "Bussiness Days"); ?>
                        </a>
                    </li>
                    <li><a class="" href="/appointmentpro/provider/service/id/(ID)">
                         <?php echo p__("appointmentpro", "Services"); ?>
                        </a>
                    </li>                    
                    <li class="divider"></li>
                    <li><a class="delete-provider" href="/appointmentpro/provider/delete/id/(ID)">
                        <?php echo p__("appointmentpro", "Delete"); ?>
                       </a>
                   </li>
                </ul>
              </li>
            </ul>
         </td>
       
    </tr>`;

function rowWriter(rowIndex, record, columns, cellWriter) {
    return rowTemplate
        .replace(/\(ID\)/g, record.provider_id)
        .replace(/\(IMAGE\)/g, record.image)
        .replace(/\(NAME\)/g, record.name)
        .replace(/\(EMAIL\)/g, record.email)
        .replace(/\(MOBILENUMBER\)/g, record.mobile_number)
        .replace(/\(DESIGNATION\)/g, record.designation)
        .replace(/\(NAME\)/g, record.name)
        .replace(/\(MOBILEUSER\)/g, record.is_mobile_user)
        .replace(/\(ROLE\)/g, record.user_role)
        .replace(/\(LOCATION\)/g, record.location_name)
        .replace(/\(ISACTIVE\)/g, record.is_active);
}
$.dynatableSetup({
    table: {
        defaultColumnIdStyle: 'noStyle'
    },
    features: {
        paginate: true,
        sort: false,
        pushState: true,
        search: true,
        recordCount: false,
        perPageSelect: false,
    },
});

let tableCustomers = $('#dynamic-provider');

tableCustomers.bind('dynatable:preinit', function(e, dynatable) {
    dynatable.utility.textTransform.noStyle = function(text) {
        return text;
    };
});

tableCustomers.bind('dynatable:afterProcess', function(e, data) {
    uriParams = data.queries;
});

tableCustomers.bind('dynatable:push', function(e, dynatable) {
    uriParams = dynatable.queries;
});

// And on the table
tableCustomers.dynatable({
    dataset: {
        ajax: true,
        ajaxUrl: '/appointmentpro/provider/find-all',
        ajaxOnLoad: true,
        records: [],
        perPageDefault: 25
    },
    inputs: {
        processingText: '<?php echo __jss("Loading ...") ?>',
        searchPlaceholder: '<?php echo __jss("Search provider ...") ?>',
        recordCountText: '<?php echo __jss("Showing") ?> ',
        filteredFrom: ' (<?php echo __jss("filtered from #TOTAL# total records") ?>)',
        recordText: '<?php echo __jss("record") ?>',
        recordTextPlural: '<?php echo __jss("records") ?>',
        textOf: '<?php echo __jss("of") ?>',
        textTo: '<?php echo __jss("to") ?>',
        queries: $('.dt-search')
    },
    writers: {
        _rowWriter: rowWriter
    }
});

$(document).off("click", ".delete-provider");
$(document).on("click", ".delete-provider", function(e) {
    e.preventDefault();
    let deleteHref = $(this).attr("href");
    swal({
        title: "<?php echo P__("appointmentpro", "Confirmation") ?>",
        text: "<?php echo P__("appointmentpro", "Are you sure you want to delete this provider?") ?>",
        showCancelButton: true,
        confirmButtonColor: '#0099C7',
        confirmButtonText: "<?php echo P__("appointmentpro", "Yes, delete!")?>",
        cancelButtonText: "<?php echo P__("appointmentpro", "No, go back") ?>",
        buttons: true
    }, function(value) {
        if (!value) {
            return false;
        }

        formget(deleteHref, {},
            function(data) {
                feature_form_success(data.message);
                // Reload only on success and when done!
                setTimeout(function() {
                    location.reload();
                }, 1500)
            },
            function(data) {
                feature_form_error(JSON.parse(data.responseText).message);
            },
            false);
    });
});



var $tabs = $('#dynamic-provider');
$(document).ready(function() {
    $("tbody.connectedSortable")
        .sortable({
            connectWith: ".connectedSortable",
            appendTo: $tabs,
            helper: "clone",
            cursor: 'move',
            zIndex: 999990,
            stop: function(event, ui) {
                var data = $(this).sortable('toArray');

                $.ajax({
                    method: "POST",
                    url: "<?php echo $this->getUrl('appointmentpro/provider/sortable'); ?>",
                    data: {
                        data: data
                    }
                }).done(function(msg) {});
            }
        })
        .disableSelection();
});
</script>
<style>
.table {
    width: 100%;
    overflow: auto;
}

.dropdown-menu {
    min-width: auto;
}
</style>